### ISSUE TITLE
修改密码有个bug

### ISSUE THREAD

**Issue by dadadong** [getzealot/zealot#124]
<img width="1170" alt="图片" src="https://user-images.githubusercontent.com/13832911/72660105-ee90c780-3a03-11ea-88ce-63f447e44e38.png">

**Comment by dadadong** [comment]
如图，三个选项框标识不准，红字标识才是真实的取值

**Comment by icyleaf** [comment]
😳 下周一我看看

--
/**
* About me
*
* @author icyleaf
* @url http://icyleaf.com
* @version always beta
*/
2020年1月18日 +0800 15:09 dadadong <notifications@github.com>，写道：

**Comment by icyleaf** [comment]
本地化 devise 出了问题，等待 [构建](https://github.com/getzealot/zealot/commit/92f453e77306d94449c746a9b20ea5e901748cf1/checks?check_suite_id=409493284) 结束后就可以 pull 下最新版本了

**Comment by icyleaf** [comment]
有问题再反馈，我先关了
