### ISSUE TITLE
关于自签名证书问题

### ISSUE THREAD

**Issue by li5414** [getzealot/zealot#179]
因为本身内网环境局域网使用，所以准备使用自签名证书,我是在win10部署的
== Configuring Deploy ==
How do you deploy?
  Use [L]et's Encryt SSL (default)
  Use [S]elf-signed SSL
  Do [n]ot use SSL?
S

== Configuring self signed SSL/TLS cert ==
Generating self-signed cert for zealot.test

打印到这就结束了,最终证书没有生成成功,rootfs\etc\certs里面是空的,env里面也没有写入，docker-compose.yml 没有创建

**Comment by icyleaf** [comment]
这步需要一点时间，需要拉取一个 docker image 来生成

**Comment by icyleaf** [comment]
由于太长时间没有得到恢复本问题会自动被关闭，如果您还有问题可以重新开启或提交新问题。感谢你对于 Zealot 的关注！

**Comment by leokwsw** [comment]
> 这步需要一点时间，需要拉取一个 docker image 来生成

就算自行拉取了caddy:2-alpine也是到Configuring self signed SSL/TLS cert这行之后就结束了
